<?php

/**
 * @file
 * A Shibboleth and UW Groups authentication module. 
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uwauth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.uwauth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements support for Shibboleth with UW Groups') . '</p>';
      return $output;
  }
}
